---
  extends: ['eslint:all']
  env:
    es6: true
    browser: true
  rules:
    array-bracket-newline: 0
    array-bracket-spacing: 0
    array-element-newline: 0
    arrow-parens: ["error", "as-needed"]
    capitalized-comments: 0
    computed-property-spacing: 0
    curly: 0
    dot-location: 0
    eol-last: 0    # We don't need an extra EOL at the end of file.
    func-names: 0
    func-style: 0
    id-length: 0
    indent: 0     # ["error", 4, { "SwitchCase": 0 }]
    keyword-spacing: 0
    line-comment-position: 0
    linebreak-style: 0
    max-len: [1, { code: 120 }]
    max-lines: [1, { max: 300, skipBlankLines: true, skipComments: true}]
    max-params: [1, {max: 6}]
    max-statements: [2, {max: 20}]
    multiline-comment-style: 0
    multiline-ternary: 0
    new-cap: 0    # Functions must not start with a capital letter.
    newline-per-chained-call: 0
    no-bitwise: 0
    no-console: [1, { allow: ["warn", "error"] }]
    no-continue: 0
    no-extra-parens: [1, 'all', { nestedBinaryExpressions: false }]
    no-implicit-globals: 0 # Because we always work in modules.
    no-inline-comments: 0
    no-magic-numbers: [1, { "ignore": [0, 1] }]
    no-mixed-operators: ["error", {"groups": [["&", "|", "^", "~", "<<", ">>", ">>>"], ["&&", "||"]]}]
    no-negated-condition: 0
    no-plusplus: 0  # I want to be able to use i++.
    no-ternary: 0
    no-underscore-dangle: [0, { "allowAfterThis": true }]
    no-use-before-define: [2, { functions: false, classes: true }]
    object-curly-spacing: 0
    object-property-newline: [2, { allowAllPropertiesOnSameLine: true}]
    object-shorthand: 1    # Can't do this because of IE11
    one-var: 0
    padded-blocks: 0
    prefer-arrow-callback: 0
    prefer-destructuring: 0
    prefer-rest-params: 1 # IE11 prevents us to use this.
    prefer-spread: 1 # IE11 prevents us to use this.
    quote-props: 0
    quotes: 0    # We can put single or double quotes if we want to.
    sort-keys: 0
    sort-vars: 0
    space-before-function-paren: 0
    space-in-parens: 0
    strict: [2, 'global']
    valid-jsdoc: [2, { requireReturn: false }]
  globals:
    console: false
    exports: false
    module: false
    require: false
    _: true
